# fly.toml file generated for gacituacompanyms on 2023-03-29T10:14:39-03:00

app = "gacituacompanyms"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "scl"
processes = []

[env]
  SPRING_DATASOURCE_PASSWORD = "u2nDqbi3Jr6zAa4"
  SPRING_DATASOURCE_URL = "jdbc:postgresql://gacituacompanypostgres.internal:5432/gacituadb"
  SPRING_DATASOURCE_USERNAME = "postgres"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 9000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
