package com.gcom.operacional.entity;
// Generated 10-02-2023 09:10:59 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BillOfBuy generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "bill_of_buy")
public class BillOfBuy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private BillOfBuyState billOfBuyState;
	private Provider provider;
	private String username;
	private Date generationDate;
	private Date updateDate;
	private BigDecimal discount;
	private BigDecimal iva;
	private String additionalInformation;
	private Set<BillOfBuyReverse> billOfBuyReverses = new HashSet<BillOfBuyReverse>(0);
	private Set<BillOfBuyProduct> billOfBuyProducts = new HashSet<BillOfBuyProduct>(0);

	public BillOfBuy() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bill_of_buy_state", nullable = false)
	public BillOfBuyState getBillOfBuyState() {
		return this.billOfBuyState;
	}

	public void setBillOfBuyState(BillOfBuyState billOfBuyState) {
		this.billOfBuyState = billOfBuyState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_provider", nullable = false)
	public Provider getProvider() {
		return this.provider;
	}

	public void setProvider(Provider provider) {
		this.provider = provider;
	}

	@Column(name = "username", nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "generation_date", length = 29)
	public Date getGenerationDate() {
		return this.generationDate;
	}

	public void setGenerationDate(Date generationDate) {
		this.generationDate = generationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "discount", precision = 0, scale = 0)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "iva", precision = 0, scale = 0)
	public BigDecimal getIva() {
		return this.iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}

	@Column(name = "additional_information", length = 300)
	public String getAdditionalInformation() {
		return this.additionalInformation;
	}

	public void setAdditionalInformation(String additionalInformation) {
		this.additionalInformation = additionalInformation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "billOfBuy")
	public Set<BillOfBuyReverse> getBillOfBuyReverses() {
		return this.billOfBuyReverses;
	}

	public void setBillOfBuyReverses(Set<BillOfBuyReverse> billOfBuyReverses) {
		this.billOfBuyReverses = billOfBuyReverses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "billOfBuy")
	public Set<BillOfBuyProduct> getBillOfBuyProducts() {
		return this.billOfBuyProducts;
	}

	public void setBillOfBuyProducts(Set<BillOfBuyProduct> billOfBuyProducts) {
		this.billOfBuyProducts = billOfBuyProducts;
	}

}
