package com.gcom.operacional.entity;
// Generated 10-02-2023 09:10:59 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InventoryTweaks generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "inventory_tweaks")
public class InventoryTweaks implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String username;
	private Date dateInventoryTweaks;
	private String reason;
	private String inventoryTweaksState;
	private String additionalInformation;
	private Set<InventoryTweaksProduct> inventoryTweaksProducts = new HashSet<InventoryTweaksProduct>(0);

	public InventoryTweaks() {
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_inventory_tweaks", nullable = false, length = 29)
	public Date getDateInventoryTweaks() {
		return this.dateInventoryTweaks;
	}

	public void setDateInventoryTweaks(Date dateInventoryTweaks) {
		this.dateInventoryTweaks = dateInventoryTweaks;
	}

	@Column(name = "reason", length = 300)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}
	
	@Column(name = "inventory_tweaks_state", nullable = false, length = 150)
	public String getInventoryTweaksState() {
		return this.inventoryTweaksState;
	}

	public void setInventoryTweaksState(String inventoryTweaksState) {
		this.inventoryTweaksState = inventoryTweaksState;
	}

	@Column(name = "additional_information", length = 300)
	public String getAdditionalInformation() {
		return this.additionalInformation;
	}

	public void setAdditionalInformation(String additionalInformation) {
		this.additionalInformation = additionalInformation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inventoryTweaks")
	public Set<InventoryTweaksProduct> getInventoryTweaksProducts() {
		return this.inventoryTweaksProducts;
	}

	public void setInventoryTweaksProducts(Set<InventoryTweaksProduct> inventoryTweaksProducts) {
		this.inventoryTweaksProducts = inventoryTweaksProducts;
	}

}
