package com.gcom.operacional.entity;
// Generated 22-06-2023 12:38:09 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OperationLog generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "operation_log")
public class OperationLog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String operationUsername;
	private String operationFullName;
	private Date operationDate;
	private String operationType;
	private String operationCurrentState;
	private Long operationIdObject;
	private Set<OperationLogProduct> operationLogProducts = new HashSet<OperationLogProduct>(0);
	private Set<OperationLogState> operationLogStates = new HashSet<OperationLogState>(0);

	public OperationLog() {
	}
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "operation_username", length = 30)
	public String getOperationUsername() {
		return this.operationUsername;
	}

	public void setOperationUsername(String operationUsername) {
		this.operationUsername = operationUsername;
	}

	@Column(name = "operation_full_name", length = 50)
	public String getOperationFullName() {
		return this.operationFullName;
	}

	public void setOperationFullName(String operationFullName) {
		this.operationFullName = operationFullName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "operation_date", length = 29)
	public Date getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(Date operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "operation_type", nullable = false, length = 300)
	public String getOperationType() {
		return this.operationType;
	}

	public void setOperationType(String operationType) {
		this.operationType = operationType;
	}

	@Column(name = "operation_current_state", nullable = false, length = 300)
	public String getOperationCurrentState() {
		return this.operationCurrentState;
	}

	public void setOperationCurrentState(String operationCurrentState) {
		this.operationCurrentState = operationCurrentState;
	}

	@Column(name = "operation_id_object", nullable = false)
	public long getOperationIdObject() {
		return this.operationIdObject;
	}

	public void setOperationIdObject(long operationIdObject) {
		this.operationIdObject = operationIdObject;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operationLog")
	public Set<OperationLogProduct> getOperationLogProducts() {
		return this.operationLogProducts;
	}

	public void setOperationLogProducts(Set<OperationLogProduct> operationLogProducts) {
		this.operationLogProducts = operationLogProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operationLog")
	public Set<OperationLogState> getOperationLogStates() {
		return this.operationLogStates;
	}

	public void setOperationLogStates(Set<OperationLogState> operationLogStates) {
		this.operationLogStates = operationLogStates;
	}

}
