package com.gcom.operacional.entity;
// Generated 03-07-2023 09:04:03 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OperationLogState generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "operation_log_state")
public class OperationLogState implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private OperationLog operationLog;
	private String operationUsername;
	private String operationFullName;
	private Date operationDate;
	private String operationState;

	public OperationLogState() {
	}
	
	public OperationLogState(Long id, OperationLog operationLog, String operationUsername, String operationFullName,
			Date operationDate, String operationState) {
		super();
		this.id = id;
		this.operationLog = operationLog;
		this.operationUsername = operationUsername;
		this.operationFullName = operationFullName;
		this.operationDate = operationDate;
		this.operationState = operationState;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_operation_log", nullable = false)
	public OperationLog getOperationLog() {
		return this.operationLog;
	}

	public void setOperationLog(OperationLog operationLog) {
		this.operationLog = operationLog;
	}

	@Column(name = "operation_username", length = 30)
	public String getOperationUsername() {
		return this.operationUsername;
	}

	public void setOperationUsername(String operationUsername) {
		this.operationUsername = operationUsername;
	}

	@Column(name = "operation_full_name", length = 50)
	public String getOperationFullName() {
		return this.operationFullName;
	}

	public void setOperationFullName(String operationFullName) {
		this.operationFullName = operationFullName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "operation_date", length = 29)
	public Date getOperationDate() {
		return this.operationDate;
	}

	public void setOperationDate(Date operationDate) {
		this.operationDate = operationDate;
	}

	@Column(name = "operation_state", nullable = false, length = 300)
	public String getOperationState() {
		return this.operationState;
	}

	public void setOperationState(String operationState) {
		this.operationState = operationState;
	}

}
