package com.gcom.operacional.entity;
// Generated 10-02-2023 09:10:59 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrderNoteState generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "order_note_state")
public class OrderNoteState implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String nameState;
	private String descState;
	private Set<OrderNote> orderNotes = new HashSet<OrderNote>(0);

	public OrderNoteState() {
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name_state", nullable = false, length = 30)
	public String getNameState() {
		return this.nameState;
	}

	public void setNameState(String nameState) {
		this.nameState = nameState;
	}

	@Column(name = "desc_state", nullable = false, length = 150)
	public String getDescState() {
		return this.descState;
	}

	public void setDescState(String descState) {
		this.descState = descState;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderNoteState")
	public Set<OrderNote> getOrderNotes() {
		return this.orderNotes;
	}

	public void setOrderNotes(Set<OrderNote> orderNotes) {
		this.orderNotes = orderNotes;
	}

}
