package com.gcom.operacional.entity;
// Generated 10-04-2023 09:01:35 by Hibernate Tools 4.3.6.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderNoteReverse generated by hbm2java
 */
@Entity
@Table(schema = "public",  name = "order_note_reverse")
public class OrderNoteReverse implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private OrderNote orderNote;
	private String updateName;
	private Date updateDate;
	private Long numberOfCreditNote;
	private Date dateOfCreditNote;
	private String additionalInformation;

	public OrderNoteReverse() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_order_note", nullable = false)
	public OrderNote getOrderNote() {
		return this.orderNote;
	}

	public void setOrderNote(OrderNote orderNote) {
		this.orderNote = orderNote;
	}

	@Column(name = "update_name", nullable = false, length = 50)
	public String getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "number_of_credit_note")
	public Long getNumberOfCreditNote() {
		return this.numberOfCreditNote;
	}

	public void setNumberOfCreditNote(Long numberOfCreditNote) {
		this.numberOfCreditNote = numberOfCreditNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_credit_note", length = 29)
	public Date getDateOfCreditNote() {
		return this.dateOfCreditNote;
	}

	public void setDateOfCreditNote(Date dateOfCreditNote) {
		this.dateOfCreditNote = dateOfCreditNote;
	}

	@Column(name = "additional_information", length = 1000)
	public String getAdditionalInformation() {
		return this.additionalInformation;
	}

	public void setAdditionalInformation(String additionalInformation) {
		this.additionalInformation = additionalInformation;
	}

}
