package com.gcom.operacional.entity;
// Generated 10-02-2023 09:10:59 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderNote generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "order_note")
public class OrderNote implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Client client;
	private OrderNoteState orderNoteState;
	private String updateName;
	private Date generationDate;
	private Date updateDate;
	private Date deliveryDate;
	private BigDecimal discount;
	private BigDecimal iva;
	private boolean showAdditionalInformation;
	private String additionalInformation;
	private String numberOfBill;
	private Date dateOfBill;
	private String numberOfPurchaseOrder;
	private Date dateOfPurchaseOrder;
	private String deliveryType;
	private String transport;
	private Set<OrderNoteProduct> orderNoteProducts = new HashSet<OrderNoteProduct>(0);
	private Set<OrderNoteReverse> orderNoteReverses = new HashSet<OrderNoteReverse>(0);

	public OrderNote() {
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_client", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_order_note_state", nullable = false)
	public OrderNoteState getOrderNoteState() {
		return this.orderNoteState;
	}

	public void setOrderNoteState(OrderNoteState orderNoteState) {
		this.orderNoteState = orderNoteState;
	}

	@Column(name = "update_name", nullable = false, length = 50)
	public String getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "generation_date", length = 29)
	public Date getGenerationDate() {
		return this.generationDate;
	}

	public void setGenerationDate(Date generationDate) {
		this.generationDate = generationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delivery_date", length = 29)
	public Date getDeliveryDate() {
		return this.deliveryDate;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	@Column(name = "discount", precision = 0, scale = 0)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "iva", nullable = false, precision = 0, scale = 0)
	public BigDecimal getIva() {
		return this.iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}

	@Column(name = "show_additional_information", nullable = false)
	public boolean isShowAdditionalInformation() {
		return this.showAdditionalInformation;
	}

	public void setShowAdditionalInformation(boolean showAdditionalInformation) {
		this.showAdditionalInformation = showAdditionalInformation;
	}

	@Column(name = "additional_information", length = 1000)
	public String getAdditionalInformation() {
		return this.additionalInformation;
	}

	public void setAdditionalInformation(String additionalInformation) {
		this.additionalInformation = additionalInformation;
	}

	@Column(name = "number_of_bill", length = 50)
	public String getNumberOfBill() {
		return this.numberOfBill;
	}

	public void setNumberOfBill(String numberOfBill) {
		this.numberOfBill = numberOfBill;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_bill", length = 29)
	public Date getDateOfBill() {
		return this.dateOfBill;
	}

	public void setDateOfBill(Date dateOfBill) {
		this.dateOfBill = dateOfBill;
	}

	@Column(name = "number_of_purchase_order", length = 50)
	public String getNumberOfPurchaseOrder() {
		return this.numberOfPurchaseOrder;
	}

	public void setNumberOfPurchaseOrder(String numberOfPurchaseOrder) {
		this.numberOfPurchaseOrder = numberOfPurchaseOrder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_purchase_order", length = 29)
	public Date getDateOfPurchaseOrder() {
		return this.dateOfPurchaseOrder;
	}

	public void setDateOfPurchaseOrder(Date dateOfPurchaseOrder) {
		this.dateOfPurchaseOrder = dateOfPurchaseOrder;
	}

	@Column(name = "delivery_type", length = 300)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Column(name = "transport", length = 300)
	public String getTransport() {
		return this.transport;
	}

	public void setTransport(String transport) {
		this.transport = transport;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "orderNote")
	public Set<OrderNoteProduct> getOrderNoteProducts() {
		return this.orderNoteProducts;
	}

	public void setOrderNoteProducts(Set<OrderNoteProduct> orderNoteProducts) {
		this.orderNoteProducts = orderNoteProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderNote")
	public Set<OrderNoteReverse> getOrderNoteReverses() {
		return this.orderNoteReverses;
	}

	public void setOrderNoteReverses(Set<OrderNoteReverse> orderNoteReverses) {
		this.orderNoteReverses = orderNoteReverses;
	}

}
