package com.gcom.operacional.entity;
// Generated 10-02-2023 09:10:59 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "product")
public class Product implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Model model;
	private Product product;
	private ProductType productType;
	private Sources sources;
	private UniversalGroups universalGroups;
	private BigDecimal salePrice;
	private BigDecimal netCost;
	private String rowNumb;
	private String colNumb;
	private String description;
	private int stock;
	private String providerDescription;
	private Set<BillOfBuyProduct> billOfBuyProducts = new HashSet<BillOfBuyProduct>(0);
	private Set<ProviderCode> providerCodes = new HashSet<ProviderCode>(0);
	private Set<Product> products = new HashSet<Product>(0);
	private Set<OrderNoteProduct> orderNoteProducts = new HashSet<OrderNoteProduct>(0);
	private Set<OriginalCode> originalCodes = new HashSet<OriginalCode>(0);
	private Set<QuotationProduct> quotationProducts = new HashSet<QuotationProduct>(0);
	private Set<Gloss> glosses = new HashSet<Gloss>(0);
	private Set<InventoryTweaksProduct> inventoryTweaksProducts = new HashSet<InventoryTweaksProduct>(0);

	public Product() {
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_model", nullable = false)
	public Model getModel() {
		return this.model;
	}

	public void setModel(Model model) {
		this.model = model;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_equivalent")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_product_type", nullable = false)
	public ProductType getProductType() {
		return this.productType;
	}

	public void setProductType(ProductType productType) {
		this.productType = productType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sources", nullable = false)
	public Sources getSources() {
		return this.sources;
	}

	public void setSources(Sources sources) {
		this.sources = sources;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_universal_groups", nullable = false)
	public UniversalGroups getUniversalGroups() {
		return this.universalGroups;
	}

	public void setUniversalGroups(UniversalGroups universalGroups) {
		this.universalGroups = universalGroups;
	}

	@Column(name = "sale_price", nullable = false, precision = 9, scale = 4)
	public BigDecimal getSalePrice() {
		return this.salePrice;
	}

	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

	@Column(name = "net_cost", nullable = false, precision = 9, scale = 4)
	public BigDecimal getNetCost() {
		return this.netCost;
	}

	public void setNetCost(BigDecimal netCost) {
		this.netCost = netCost;
	}

	@Column(name = "row_numb", length = 20)
	public String getRowNumb() {
		return this.rowNumb;
	}

	public void setRowNumb(String rowNumb) {
		this.rowNumb = rowNumb;
	}

	@Column(name = "col_numb", length = 20)
	public String getColNumb() {
		return this.colNumb;
	}

	public void setColNumb(String colNumb) {
		this.colNumb = colNumb;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@Column(name = "stock", nullable = false, precision = 9, scale = 0)
	public int getStock() {
		return this.stock;
	}

	public void setStock(int stock) {
		this.stock = stock;
	}

	@Column(name = "provider_description", length = 500)
	public String getProviderDescription() {
		return this.providerDescription;
	}

	public void setProviderDescription(String providerDescription) {
		this.providerDescription = providerDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<BillOfBuyProduct> getBillOfBuyProducts() {
		return this.billOfBuyProducts;
	}

	public void setBillOfBuyProducts(Set<BillOfBuyProduct> billOfBuyProducts) {
		this.billOfBuyProducts = billOfBuyProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<ProviderCode> getProviderCodes() {
		return this.providerCodes;
	}

	public void setProviderCodes(Set<ProviderCode> providerCodes) {
		this.providerCodes = providerCodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OrderNoteProduct> getOrderNoteProducts() {
		return this.orderNoteProducts;
	}

	public void setOrderNoteProducts(Set<OrderNoteProduct> orderNoteProducts) {
		this.orderNoteProducts = orderNoteProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<OriginalCode> getOriginalCodes() {
		return this.originalCodes;
	}

	public void setOriginalCodes(Set<OriginalCode> originalCodes) {
		this.originalCodes = originalCodes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<QuotationProduct> getQuotationProducts() {
		return this.quotationProducts;
	}

	public void setQuotationProducts(Set<QuotationProduct> quotationProducts) {
		this.quotationProducts = quotationProducts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<Gloss> getGlosses() {
		return this.glosses;
	}

	public void setGlosses(Set<Gloss> glosses) {
		this.glosses = glosses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "product")
	public Set<InventoryTweaksProduct> getInventoryTweaksProducts() {
		return this.inventoryTweaksProducts;
	}

	public void setInventoryTweaksProducts(Set<InventoryTweaksProduct> inventoryTweaksProducts) {
		this.inventoryTweaksProducts = inventoryTweaksProducts;
	}

}
