package com.gcom.operacional.entity;
// Generated 10-02-2023 09:10:59 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Quotation generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "quotation")
public class Quotation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Client client;
	private QuotationState quotationState;
	private String updateName;
	private String updateMail;
	private Date updateDate;
	private Date generationDate;
	private BigDecimal discount;
	private BigDecimal iva;
	private String attention;
	private String additionalInformation;
	private Set<QuotationProduct> quotationProducts = new HashSet<QuotationProduct>(0);

	public Quotation() {
	}

	@Id 
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_client", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_quotation_state", nullable = false)
	public QuotationState getQuotationState() {
		return this.quotationState;
	}

	public void setQuotationState(QuotationState quotationState) {
		this.quotationState = quotationState;
	}

	@Column(name = "update_name", nullable = false, length = 30)
	public String getUpdateName() {
		return this.updateName;
	}

	public void setUpdateName(String updateName) {
		this.updateName = updateName;
	}

	@Column(name = "update_mail", nullable = false, length = 50)
	public String getUpdateMail() {
		return this.updateMail;
	}

	public void setUpdateMail(String updateMail) {
		this.updateMail = updateMail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_date", nullable = false, length = 29)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "generation_date", length = 29)
	public Date getGenerationDate() {
		return this.generationDate;
	}

	public void setGenerationDate(Date generationDate) {
		this.generationDate = generationDate;
	}

	@Column(name = "discount", precision = 0, scale = 0)
	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	@Column(name = "iva", nullable = false, precision = 0, scale = 0)
	public BigDecimal getIva() {
		return this.iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}
	
	@Column(name = "attention", length = 200)
	public String getAttention() {
		return this.attention;
	}

	public void setAttention(String attention) {
		this.attention = attention;
	}

	@Column(name = "additional_information", length = 300)
	public String getAdditionalInformation() {
		return this.additionalInformation;
	}

	public void setAdditionalInformation(String additionalInformation) {
		this.additionalInformation = additionalInformation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "quotation")
	public Set<QuotationProduct> getQuotationProducts() {
		return this.quotationProducts;
	}

	public void setQuotationProducts(Set<QuotationProduct> quotationProducts) {
		this.quotationProducts = quotationProducts;
	}

}
