package com.gcom.operacional.entity;
// Generated 10-02-2023 09:10:59 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StorageRoom generated by hbm2java
 */
@Entity
@Table(schema = "public", name = "storage_room")
public class StorageRoom implements java.io.Serializable {

	private int id;
	private String address;
	private String status;

	public StorageRoom() {
	}

	public StorageRoom(int id, String status) {
		this.id = id;
		this.status = status;
	}

	public StorageRoom(int id, String address, String status) {
		this.id = id;
		this.address = address;
		this.status = status;
	}

	@Id @GeneratedValue

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "address", length = 100)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "status", nullable = false, length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
